pipeline {
    agent any

    environment {
        IMAGE_NAME = "student-management:prod"
    }

    stages {

        stage('Build JAR') {
            steps {
                sh '''
                cd app/student-management
                chmod +x mvnw
                ./mvnw clean package -DskipTests
                '''
            }
        }

        stage('Unit Tests') {
            steps {
                sh '''
                cd app/student-management
                ./mvnw test
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarQ') {
                    sh '''
                    cd app/student-management
                    ./mvnw sonar:sonar
                    '''
                }
            }
        }


        stage('Docker Build') {
            steps {
                sh '''
docker build -t $IMAGE_NAME -f docker/Dockerfile.prod .

                '''
            }
        }

stage('Deploy to Kubernetes') {
  steps {
    sh '''
    kubectl apply -f k8s/ --validate=false
    '''
  }
}

    }

    post {
        success {
            echo 'Pipeline SUCCESS'
        }
        failure {
            echo 'Pipeline FAILED'
        }
    }
}

